# Generated by Django 4.2.11 on 2024-04-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_instruction', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qr_code_img',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
