# Generated by Django 4.2.11 on 2024-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_instruction', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
