# Generated by Django 4.2.11 on 2024-05-06 20:02

from django.db import migrations, models
import peer_instruction.models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_instruction', '0005_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=peer_instruction.models.generate_image_filename),
        ),
    ]
