version: '3'

services:
  docs:
    image: group29final_local_docs
    container_name: group29final_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./group29final:/app/group29final:z
    ports:
      - '9000:9000'
    command: /start-docs
